version: "3.7"

services:
  app-prod:
    container_name: frontprod
    profiles: ["prod"]
    build:
      context: .
      dockerfile: docker/Dockerfile.prod
      args:
        API: $$(gp url 8080)
    image: frontprod
    ports:
      - "8000:8000"

  app-dev:
    container_name: frontdev
    profiles: ["dev"]
    tty: true
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
      args:
        API: $$(gp url 8080)
        
    volumes:
      - ./src/:/app/src:cached
      
    ports:
      - "8080:8080"