version: "3.7"
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: daly
      POSTGRES_DB: timer
    ports:
      - 5432:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  web:
    image: daly/web:1
    depends_on:
      - db
    ports:
      - 8080:3000