version: '3.9'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: daly
      POSTGRES_DB: timer
    ports:
      - 5432:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - node_network

  web:
    build: 
      dockerfile: docker/prod/Dockerfile
      args:
        API: $$(gp url 8080)
    depends_on:
      - db
    networks:
      - node_network

  proxy:
    restart: unless-stopped
    image: nginx
    ports:
      - 80:80
    depends_on:
      - web
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - node_network

networks:
  node_network:
