version: '3.9'
services:
  db:
    image: postgres
    profiles: ["dev", "prod"]
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: daly
      POSTGRES_DB: timer
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - node_network

  api-dev:
    profiles: ["dev"]
    build: 
      context: ./backend/
    depends_on:
      - db
    networks:
      - node_network
    volumes:
      - ./backend/src/:/app/src:cached
    ports:
      - "3000:3000"

  api-prod:
    profiles: ["prod"]
    command: npm run start:migrate:prod
    build: 
      context: ./backend/
    depends_on:
      - db
    networks:
      - node_network
    ports:
      - "3000:3000"

  app-prod:
    container_name: frontprod
    profiles: ["prod"]
    build:
      context: ./timetracker-frontend/
      dockerfile: docker/Dockerfile.prod
      args:
        VUE_APP_API_URL: ${API_URL}
    ports:
      - "8000:80"
    networks:
      - node_network

  app-dev:
    container_name: frontdev
    profiles: ["dev"]
    tty: true
    environment:
      - VUE_APP_API_URL=${API_URL}
    build:
      context: ./timetracker-frontend/
      dockerfile: docker/Dockerfile.dev
    volumes:
      - ./timetracker-frontend/src/:/app/src:cached
    ports:
      - "8080:8080"
    networks:
      - node_network


networks:
  node_network:
