version: '3.9'
services:
  db:
    image: postgres
    profiles: ["dev", "prod"]
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: daly
      POSTGRES_DB: timer
    ports:
      - 5432:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - node_network


  api-dev:
    profiles: ["dev"]
    build: 
      args:
        API: $$(gp url 8080)
    depends_on:
      - db
    networks:
      - node_network
    ports:
      - "3000:3000"

  api-prod:
    profiles: ["prod"]
    command: npm run start:migrate:prod
    build: 
      args:
        API: $$(gp url 8080)
    depends_on:
      - db
    networks:
      - node_network
    ports:
      - "3000:3000"

networks:
  node_network:
