# Install node dependencies 
FROM node:16.17.0 as dependencies-build
WORKDIR /app
COPY ./package.json ./
RUN npm install
COPY . .
ARG VUE_APP_DATABASE_URL=$API
RUN npm run build



FROM nginx:1.15.7-alpine as production-stage
COPY --from=dependencies-build /app/dist /usr/share/nginx/html
EXPOSE 8000
CMD ["nginx", "-g", "daemon off;"]




