# Install node dependencies 
FROM node:16.17.0 as dependencies
WORKDIR /app
COPY ./package*.json ./
RUN npm install



FROM node:16.17.0 as builder
WORKDIR /app
ADD . .
COPY --from=dependencies /app/node_modules/ /app/node_modules/
EXPOSE 8080
CMD ["npm", "run", "serve"]